use_frameworks!

# Realm: Always on the end of the file to update swift version if needed
post_install do |installer|
        installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end


# ReactiveX
target 'be.makingidea.elios' do # Change to right appId
pod 'RxSwift' ,    '~> 3.0'
pod 'RxCocoa' ,    '~> 3.0'

# Http client
pod 'Alamofire', '~> 4.0'

# Json parser
pod 'SwiftyJSON'
end

