use_frameworks!

# Realm: Always on the end of the file to update swift version if needed
post_install do |installer|
        installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

target 'be.makingidea.elios' do # Change to right appId

# Realm database
pod 'RealmSwift', '~> 2.1.2'

# ReactiveX
pod 'RxSwift' , '~> 3.0'
pod 'RxCocoa' , '~> 3.0'

# Http client
pod 'Alamofire', '~> 4.1'

# JsonObject mapper and extension for Alamofire
pod 'ObjectMapper', '~> 2.0'
pod 'AlamofireObjectMapper', '~> 4.0'

# Logging
pod 'SwiftyBeaver', '~> 1.1.1'
#pod 'Timberjack', '~> 0.0.3'
pod 'Reqres', '~> 2.0.0' # Waiting for Timberjack 0.0.3 pod

# Animation
#pod 'Spring'

# Loading and caching images 
#pod 'Kingfisher'

end

